/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:67e126c9-d09e-4fb8-8a57-fa93f0dbdd53",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MCkseCayO",
    "aws_user_pools_web_client_id": "411f2g1h4aq8tgfme1g64jtcbr",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "createProblem",
            "endpoint": "https://s4favscooa.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "instructorProblems",
            "endpoint": "https://hjre76nigb.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "studentProblems",
            "endpoint": "https://lct4f5nwaa.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "submissions",
            "endpoint": "https://xwfeyp0518.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "comparisonfunction",
            "endpoint": "https://5evh7d8063.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "createProblem",
            "region": "us-east-1"
        },
        {
            "tableName": "studentSubmissions-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "studentProblems-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "aws-parallel-diagrams141253-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
